/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ArticleDetail: typeof import('./src/components/ArticleDetail.vue')['default']
    ArticleViewer: typeof import('./src/components/ArticleViewer.vue')['default']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CommentForm: typeof import('./src/components/comment/CommentForm.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    DisplayComment: typeof import('./src/components/comment/DisplayComment.vue')['default']
    DockBar: typeof import('./src/components/DockBar.vue')['default']
    DockBarItem: typeof import('./src/components/DockBarItem.vue')['default']
    DockerBarItem: typeof import('./src/components/DockerBarItem.vue')['default']
    HomeFooter: typeof import('./src/components/HomeFooter.vue')['default']
    MdViewer: typeof import('./src/components/MdViewer.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineList: typeof import('./src/components/TimelineList.vue')['default']
    TimeTip: typeof import('./src/components/TimeTip.vue')['default']
    TopGradient: typeof import('./src/components/TopGradient.vue')['default']
  }
}
