name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Build project
      run: cd deploy && ./build.sh

    - name: Create tar archive
      run: tar -czf ancy.tar.gz deploy/

    - name: Get version from tag
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        echo "Version: $VERSION"


    - name: Extract changelog
      if: startsWith(github.ref, 'refs/tags/')
      id: changelog
      run: |
        CHANGELOG_CONTENT=$(awk "/# ${VERSION}/,/# [0-9]/" CHANGELOG.md | grep -v "^# [0-9]")
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "CHANGELOG=$CHANGELOG_CONTENT" >> $GITHUB_ENV
        echo "Changelog: $CHANGELOG_CONTENT"


    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ancy.tar.gz
        body: ${{ env.CHANGELOG }}
